### ISSUE TITLE
Default import is not supported

### ISSUE THREAD

**Issue by whalemare** [goatandsheep/react-native-dotenv#113]
- [x] Tried the troubleshooting Wiki
- [x] Followed the migration Wiki

**Describe the bug**
I was trying export all config keys as default, but have the next error:
```
src/config.ts: Default import is not supported
> 1 | import Environment from '@env';
    |        ^^^^^^^^^^^
```

**To Reproduce**
Code to reproduce the behavior:
```ts
import Environment from '@env';
export const config = assertEnvironment(Environment);

function assertEnvironment(config: any): MyTypedEnvironment {
  // some code for throw error if key not exists
}
```
**Expected behavior**
Expected that I can export all keys in one single const variable, to use it anywhere I want.

**Comment by goatandsheep** [comment]
Hi @whalemare unfortunately this is not something that is even potentially possible. Even the regular `dotenv` module does not work in this way. It has always been something you need to whitelist one variable at a time from `process.env`. if you really want, create an object and whitelist the attributes you put into it.

Are you trying to do error handling for this module? Maybe there's a misunderstanding.

**Comment by whalemare** [comment]
Hi. Thank you for quick answer.
Yes, maybe error handling is unnecessary here.

**Comment by goatandsheep** [comment]
@whalemare lmk if you need any more help or if I can close this

**Comment by whalemare** [comment]
We can close it, thank you

**Comment by tkodev** [comment]
> Hi @whalemare unfortunately this is not something that is even potentially possible. Even the regular `dotenv` module does not work in this way. It has always been something you need to whitelist one variable at a time from `process.env`. if you really want, create an object and whitelist the attributes you put into it.

dotenv seems to put all the variables into process.env without whitelisting. Is this something a module would be able to do ? (inserting vars into process.env)

**Comment by goatandsheep** [comment]
No not really possible to push something across all versions because it'll overwrite a lot of built in values from react and react native and stuff. This library used to not touch process.env at all (would still have lots of values). Now it adds to it whatever people ask. However for your own app you can look into the option to use allowList in your build options
