### ISSUE TITLE
Question: Multi-env and caching

### ISSUE THREAD

**Issue by Esxiel** [goatandsheep/react-native-dotenv#115]
First of all, thanks for the library, the multi-env feature it provides makes it much better.

I have a question about the multi-env and the caching...
I understand that the .env.production / .env.development (defined environment variables) overwrite the general .env
> The base set of variables will be .env and the environment-specific variables will overwrite them.
as stated in the readme... but does this work without resetting one's cache?

e.g. I have a .env and a .env.production. I `yarn start` to run a bundler for fixing a bug on a debug build. I then stop the bundler and re- `yarn start` before proceeding to "Archive" using XCode to distribute my app. Will the Archive app use values from the .env or .env.production?

I've had a problem with the .env variables and I'm just trying to figure out if it was the caching or something else.

**Comment by goatandsheep** [comment]
What happens if you do `yarn start --reset-cache`?

**Comment by Esxiel** [comment]
Huh, I tried it again today and it seems like it's not even reading my .env.production even after I `yarn start --reset-cache` , but I swear it worked at least once before...

**Comment by Esxiel** [comment]
Am I misunderstanding the priority?
Like is it actually
(Release) .env > .env.production
(Debug) .env > .env.development

rather than 
(Release) .env.production
(Debug) .env.development

**Comment by goatandsheep** [comment]
In general you shouldn't need `APP_ENV` but  it's there in case you need it. By default the library uses your babel environment which as you said release / production , debug / development.

I think you meant
.env < .env.development
And
.env < .env.production

However if the babel env is not reporting properly, it will default to .env.development. If you can't figure out why your production environment is reporting development, easiest thing is to just use app_env=production
