### ISSUE TITLE
using with ESlint

### ISSUE THREAD

**Issue by ph98** [goatandsheep/react-native-dotenv#120]
Hi 
When i use this line 
`import { GOOGLE_WEBCLIENTID } from '@env';`

I'll face this error from ESlint: 
`Unable to resolve path to module '@env'.eslintimport/no-unresolved`
of course I can use disable for this line eslint. but isn't there a better way? 
thanks.

**Comment by goatandsheep** [comment]
I'll take a proper look later this week but for now try to either add `@env` as a constant in your babel config or change `@env` to `react-native-dotenv` as your `moduleName` in your babel and then also in the import line.

**Comment by junqdu** [comment]
> change @env to react-native-dotenv as your moduleName in your babel and then also in the import line.
This worked for me, @goatandsheep thanks!

**Comment by unit-002** [comment]
same here when importing google web client ID I also get 

`unable to resolve module `fs` from `node_modules\\react-native-dotenv\index.js: `fs` could not be found within the project`

but if I import other key it works fine. I am only having this issue with google web client ID.

**Comment by goatandsheep** [comment]
@unit-002 is your key in the .env file? Also do not install the library as a dependency only Dev dependency. You may also want to check your babel config in the troubleshooting guide in the wiki

**Comment by unit-002** [comment]
> 
> 
> @unit-002 is your key in the .env file? Also do not install the library as a dependency only Dev dependency. You may also want to check your babel config in the troubleshooting guide in the wiki

yes all are in the .env file

**Comment by goatandsheep** [comment]
Huh! I'll add a test. I did a quick search and found this example ID in the docs: `1234567890-abc123def456.apps.googleusercontent.com
`

**Comment by unit-002** [comment]
> 
> 
> Huh! I'll add a test. I did a quick search and found this example ID in the docs: `1234567890-abc123def456.apps.googleusercontent.com `

yes that is how google id looks like

**Comment by goatandsheep** [comment]
sorry that isn't it. tests passed despite the longer Google ID. There may be a caching issue? or an issue with how you've configured the .env file. take a look to see how cache clearing is done

**Comment by unit-002** [comment]
hmm, I already yarn cache clean, yarn start --reset-cache, npm cache clean --force, rebuild my app, but still same error. Don't know why, but my onesignal setAppID and channel ID is importing I also don't know why.

**Comment by goatandsheep** [comment]
So the cache issue is showing up in every other issue. If this comes up again can you try this and let me know? https://www.npmjs.com/package/react-native-clean-project

**Comment by unit-002** [comment]
> 
> 
> So the cache issue is showing up in every other issue. If this comes up again can you try this and let me know? https://www.npmjs.com/package/react-native-clean-project

Sure, thanks
