### ISSUE TITLE
What is white list and blacklist?

### ISSUE THREAD

**Issue by Luckygirlllll** [goatandsheep/react-native-dotenv#121]
Does it mean that if env file is submitted to the repository, variables which is in the blacklist wouldn''t be added to git? 
Or this blacklist and whitelist do something else?

**Comment by goatandsheep** [comment]
@Luckygirlllll that's actually it 😊 blacklist will make sure certain environment variables are not included nor will overwrite environment variables somehow imported in other ways

**Comment by goatandsheep** [comment]
closing as this should be moved to discussions
