### ISSUE TITLE
How to mix .env variables with process.env variables?

### ISSUE THREAD

**Issue by isonlaxman** [goatandsheep/react-native-dotenv#134]
This might be a dumb question, but I'm not sure how to best approach this problem.

So far, I've just built the app locally while we were in development. Now that we've released our React Native app to iOs AppStore, I want to use cloud build to avoid silly errors. Specifically, I'm using AppCenter by Microsoft. 

I don't want to push my .env file to the repo even if it's private, so I want to use environment variables in the cloud build. Is there a way to mix that with this library? So it would use the .env file on a local build and use process.env variables on the cloud build? Happy to provide more details if that was unclear

**Comment by goatandsheep** [comment]
Thanks for the question. Set the variables in app center as such: https://docs.microsoft.com/en-us/appcenter/build/custom/variables/

Make sure to add your `.env` files to gitignore!

**Comment by goatandsheep** [comment]
Closing this. Feel free to continue in discussions.
