### ISSUE TITLE
@env could not be found within the project

### ISSUE THREAD

**Issue by MaganAnkur** [goatandsheep/react-native-dotenv#141]
![simulator_screenshot_2F90FE7A-53E9-4E64-9B08-92B18C920372](https://user-images.githubusercontent.com/42070594/113722416-66591980-96be-11eb-9beb-000281c72da1.png)

.babelrc
{
    "presets": [
    "module:metro-react-native-babel-preset",
    ],
    "plugins": [
        ["module:react-native-dotenv", {
          "moduleName": "@env",
          "path": ".env",
          "blacklist": null,
          "whitelist": null,
          "safe": false,
          "allowUndefined": true
        }]
      ]
}

**Comment by goatandsheep** [comment]
Just wondering. Did you clear the cache and try again?

**Comment by MaganAnkur** [comment]
> Just wondering. Did you clear the cache and try again?

Thanks @goatandsheep for your response.

 I tried below:
- watchman watch-del-all
- rm -rf node_modules
- npm start --reset-cache

**Comment by goatandsheep** [comment]
very strange. the only thing I can think of is [this](https://github.com/facebook/react-native/issues/29351#issuecomment-657929014)

**Comment by MaganAnkur** [comment]
> very strange. the only thing I can think of is [this](https://github.com/facebook/react-native/issues/29351#issuecomment-657929014) (referenced in [additional troubleshooting wiki](https://github.com/goatandsheep/react-native-dotenv/wiki/Additional-Troubleshooting#2)). but tbh, it doesn't look easy

thanks @goatandsheep this fixes the issue, i changed presets to plugin in babel.config.

**Comment by MaganAnkur** [comment]
reopening this as when I tried again after closing the bundler, it is coming again

**Comment by PepeValenzuela98** [comment]
same issue any solution :/

**Comment by PepeValenzuela98** [comment]
i changed 
`import { BACKEND_URL } from 'react-native-dotenv`

for

`import { BACKEND_URL } from '@env`

and works

**Comment by MaganAnkur** [comment]
@PepeValenzuela98 could you pls copy your babel.config or .babelrc here for reference

**Comment by PepeValenzuela98** [comment]
@MaganAnkur sure

```
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    [
      'module:react-native-dotenv',
      {
        moduleName: '@env',
        path: '.env',
        blacklist: null,
        whitelist: null,
        safe: false,
        allowUndefined: true,
      },
    ],
  ],
};

```

**Comment by MaganAnkur** [comment]
> @MaganAnkur sure
> 
> ```
> module.exports = {
>   presets: ['module:metro-react-native-babel-preset'],
>   plugins: [
>     [
>       'module:react-native-dotenv',
>       {
>         moduleName: '@env',
>         path: '.env',
>         blacklist: null,
>         whitelist: null,
>         safe: false,
>         allowUndefined: true,
>       },
>     ],
>   ],
> };
> ```

Thanks I have the same but issue still persists.

**Comment by PepeValenzuela98** [comment]
make sure your .env file is at the root of your project

**Comment by MaganAnkur** [comment]
> make sure your .env file is at the root of your project

Yeah, its at root only.
![Screen Shot 2021-04-06 at 6 52 05 PM](https://user-images.githubusercontent.com/42070594/113787528-32efac80-9709-11eb-9513-b94f81356dc0.png)

**Comment by PepeValenzuela98** [comment]
I configure it in babel.config.js if you have not done it it would not hurt to try

**Comment by MaganAnkur** [comment]
> I configure it in babel.config.js if you have not done it it would not hurt to try

@PepeValenzuela98 Thanks it resolves the issue.

**Comment by jupitercow** [comment]
After @PepeValenzuela98 's comment above, I removed this:

`import { VIEW_URL } from "@env"`

And add this to my react module instead:

`import { VIEW_URL } from "react-native-dotenv"`

And now it is working for me...

**babel.config.js**:

```
module.exports = function (api) {
  api.cache(true)
  return {
    presets: ["babel-preset-expo"],
    plugins: [
      [
        "module:react-native-dotenv",
        {
          moduleName: "react-native-dotenv",
        },
      ],
    ],
  }
}

```

**Comment by Tasluf665** [comment]
Make sure you import react and react-native first to use @env

import react from "react";
import { View } from "react-native";

import {
  API_KEY,
  AUTH_DOMAIN,
  PROJECT_ID,
  STORAGE_BUCKET,
  MESSAGING_SENDER_ID,
  APP_ID,
} from "@env";

export default {
  API_KEY,
  AUTH_DOMAIN,
  PROJECT_ID,
  STORAGE_BUCKET,
  MESSAGING_SENDER_ID,
  APP_ID,
};
Like this.
This solves my problem.

**Comment by Boukezzoula** [comment]
> After @PepeValenzuela98 's [comment](https://github.com/goatandsheep/react-native-dotenv/issues/141#issuecomment-814483297) above, I removed this from my React component:
> 
> `import { VIEW_URL } from "@env"`
> 
> And added this instead:
> 
> `import { VIEW_URL } from "react-native-dotenv"`
> 
> And now it is working for me...
> 
> **babel.config.js**:
> 
> ```
> module.exports = function (api) {
>   api.cache(true)
>   return {
>     presets: ["babel-preset-expo"],
>     plugins: [
>       [
>         "module:react-native-dotenv",
>         {
>           moduleName: "react-native-dotenv",
>         },
>       ],
>     ],
>   }
> }
> ```

this fixed it for me

**Comment by hugogaytan10** [comment]
npm start -- --reset-cache

THIS FIXED IT FOR ME

**Comment by kashifdynamics205** [comment]
> react-native-dotenv

I pasted this code in babel.config.js and somehow the asked issue got resolved the env file starts working for other components

**Comment by kashifdynamics205** [comment]
```
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    [
      'module:react-native-dotenv',
      {
        moduleName: '@env',
        path: '.env',
        blacklist: null,
        whitelist: null,
        safe: false,
        allowUndefined: true,
      },
    ],
  ],
};

```

pasting this code in my babel.config.js somehow solved the requested issue.
