### ISSUE TITLE
Version 2.2.0 creating Babel issues in other packages?

### ISSUE THREAD

**Issue by xRiot** [goatandsheep/react-native-dotenv#15]
For more context, please refer to this issue report [react-native#29314](https://github.com/facebook/react-native/issues/29314).

After upgrading from version `0.2.0` to `2.2.0,` this package started causing errors in other non-related packages, here's a list from my environment:
```bash
node_modules/@invertase/react-native-apple-authentication/lib/version.js: [BABEL] /Users/admin/Documents/Repositories/react-native-app/node_modules/@invertase/react-native-apple-authentication/lib/version.js: Unknown option: .name. Check out https://babeljs.io/docs/en/babel-core/#options for more information about options.
node_modules/@sentry/browser/dist/integrations/trycatch.js: [BABEL] /Users/admin/Documents/Repositories/react-native-app/node_modules/@sentry/browser/dist/integrations/trycatch.js: Unknown option: .name. Check out https://babeljs.io/docs/en/babel-core/#options for more information about options.
node_modules/@sentry/browser/dist/version.js: [BABEL] /Users/admin/Documents/Repositories/react-native-app/node_modules/@sentry/browser/dist/version.js: Unknown option: .name. Check out https://babeljs.io/docs/en/babel-core/#options for more information about options.
```
Packages in my environment works fine with latest releases, expect for this one from trial and error.

I'm trying to run this with react-native `0.63.0` (if relevant) on MacOS `10.15.5` inside: `react-native run-android`.

**Comment by cardiohelge** [comment]
These BABEL errors cost me the day, because I was thinking my 0.63.0 update caused it. I went back to 0.2.0 for now.

**Comment by crobinson42** [comment]
For what it's worth - I ran into a few issues also and realized I needed to remove the `preset` that I had used with version 0.2.0 - after restarting metro and clearing cache i'm up and running.

```
// babel.config.js

module.exports = {
  plugins: [
    [
      'dotenv-import',
      {
        allowUndefined: true,
        moduleName: '@env',
        path: '.env',
        safe: false,
      },
    ],
  ],
  presets: ['module:metro-react-native-babel-preset'],
}
```

**Comment by ryanhefner** [comment]
@crobinson42 Did `'dotenv-import'` really work for you? I had to change mine to `'module:react-native-dotenv'` within `plugins` to prevent it from throwing errors on launch.

**Comment by crobinson42** [comment]
Yes, it works

**Comment by ryanhefner** [comment]
@crobinson42 Weird, doesn't work for me. I had to use the following in my `babel.config.js`:

```js
module.exports = {
  presets: ["module:metro-react-native-babel-preset"],
  plugins: [
    "module:react-native-dotenv",
  ...
  ]
};
```

Or, with the config:

```
module.exports = {
  presets: ["module:metro-react-native-babel-preset"],
  plugins: [
    [
      "module:react-native-dotenv",
      {
        moduleName: "@env",
        path: ".env",
        blacklist: null,
        whitelist: null,
        safe: false,
        allowUndefined: false
      }
    ],
    ...
  ]
};
```

Do you have the `babel-plugin-dotenv-import` package in your project as well? I do not, not sure if that’s what is different between our projects.

**Comment by Adam-Reeves** [comment]
> For what it's worth - I ran into a few issues also and realized I needed to remove the `preset` that I had used with version 0.2.0 - after restarting metro and clearing cache i'm up and running.
> 
> ```
> // babel.config.js
> 
> module.exports = {
>   plugins: [
>     [
>       'dotenv-import',
>       {
>         allowUndefined: true,
>         moduleName: '@env',
>         path: '.env',
>         safe: false,
>       },
>     ],
>   ],
>   presets: ['module:metro-react-native-babel-preset'],
> }
> ```

This worked for me, thanks :)

**Comment by JoaRiski** [comment]
Hit this issue with expo and babel, what fixed it for me was removing `module:react-native-dotenv` from presets and adding
```
            [
                "module:react-native-dotenv",
                {
                    allowUndefined: true,
                    moduleName: "@env",
                    path: ".env",
                    safe: false
                }
            ]
```
to plugins

**Comment by goatandsheep** [comment]
Hey folks thank you for creating this ticket! I merged your PR @ryanhefner . Let me know if the latest release works for you and if so I'll close this ticket.

**Comment by goatandsheep** [comment]
@JoaRiski have you noticed that there are issues with `allowUndefined: false`? It's currently the default.

**Comment by JoaRiski** [comment]
@goatandsheep I didn't happen to test that unfortunately

**Comment by goatandsheep** [comment]
@JoaRiski no problem! Let me know ☺️

**Comment by goatandsheep** [comment]
@tomcastro what is your babel config?

**Comment by goatandsheep** [comment]
@JoaRiski I ended up setting `allowUndefined` true as default

**Comment by hazyikmis** [comment]
Removing from `presets `and then putting `['module:react-native-dotenv'] `into `plugins `worked for me!

**Comment by aelarassi** [comment]
Duplicate of [https://github.com/facebook/react-native/issues/29314](https://github.com/facebook/react-native/issues/29314)

Solution :  [https://github.com/facebook/react-native/issues/29314#issuecomment-656326427](https://github.com/facebook/react-native/issues/29314#issuecomment-656326427)

**Comment by goatandsheep** [comment]
@aelarassi I highly recommend against the solution suggested in that comment as there are many security issues with that version

**Comment by xRiot** [comment]
Thank you @goatandsheep for pointing out the correct approach in https://github.com/facebook/react-native/issues/29314#issuecomment-687652155. I've updated my original comment as well.

For those unaware, please follow the [Migration Guide](https://github.com/goatandsheep/react-native-dotenv/wiki/Migration-Guide) if you're having trouble with this.

**Comment by lcnogueira** [comment]
If anyone here is facing any problem, regardless of following the Migration Guide, take a look at @JoaRiski comment above https://github.com/goatandsheep/react-native-dotenv/issues/15#issuecomment-660951831. Basically, if you set up the plugins correctly but keep the module inside the babel `preset` property, it throws an error.
