### ISSUE TITLE
add file priority to README

### ISSUE THREAD

**Issue by miwialex** [goatandsheep/react-native-dotenv#170]
Currently the README doesn't specify the priority of which the `.env` files get loaded. Based on how other packages set priority on the files, I assumed that `.env.production` had higher priority than `.env.local`, however after not getting the expected results and looking through the source code, I see that `.env.local` is the highest priority. Perhaps this should be added to the README so that people know exactly how the variables are loaded.  Also, I see that the library currently doesn't support `.env.development.local` style files, so perhaps that might be worth looking into as well.

**Comment by goatandsheep** [comment]
that is a great point!

**Comment by goatandsheep** [comment]
take a look at https://www.npmjs.com/package/dotenv-flow . I will add the link to the README

**Comment by miwialex** [comment]
@goatandsheep thanks for the reply, and this is helpful. If you look here https://www.npmjs.com/package/dotenv-flow#variables-overwritingpriority it states that `.env.local` should have lower priority than `.env.production`. However, the way `react-native-dotenv` currently works is, it treats `.env.local` as the highest priority file.

**Comment by goatandsheep** [comment]
You're 100% right. This will be a breaking change but you're right. Thanks for pointing this out! I'll fix ASAP
