### ISSUE TITLE
code push behavior

### ISSUE THREAD

**Issue by roeycohen** [goatandsheep/react-native-dotenv#175]
Hi,

When using code push, are .env values update as well or a full deployment is required?

10x!

**Comment by goatandsheep** [comment]
I've never used CodePush to be honest, but likely a full deployment is required. Basically since this is a babel plugin, it recompiles the code. Environment variables do not change from hot reloads as the environment variables are loaded at the beginning of execution. I hope this helps!

**Comment by andersonaddo** [comment]
https://github.com/goatandsheep/react-native-dotenv/issues/75#issuecomment-720526349

YMMV, I have not tried it
