### ISSUE TITLE
[Suggestion] Change from `white`/`black` to a more inclusive language (`allow`/`block`?)

### ISSUE THREAD

**Issue by caiangums** [goatandsheep/react-native-dotenv#182]
Thanks for all the work on this library and for making it robust!

### Proposal

This issue is being opened as a suggestion to move in a more inclusive terminology, removing the `white`/`black` reference and changing it to the `allow`/`block` reference (names are just a suggestion).

### Impacts and Legacy usage

Understanding legacy projects that are not being maintained and those that can schedule a change to their projects, the suggestion is to inform about the deprecation with a warning while using those terms and already accept the new ones. Thinking about this, there are 2 PRs opened:
- [x] [Deprecation Warning from the usage of `whitelist`/`blacklist` and support to `allowlist`/`blocklist` as default](https://github.com/goatandsheep/react-native-dotenv/pull/183)
- [ ] [Totally removal from `white`/`black` terms usage](https://github.com/goatandsheep/react-native-dotenv/pull/184)

The first one is not a breaking change, so it is possible to be merged and deployed as the old terms are still supported. The second one could be merged in the future version as it is a breaking change (new major version? 🤔)

### Reference

As one of many references for this change, [Rails community already changed it](https://github.com/rails/rails/pull/33681) with the small difference between `block` for `deny`.

**Comment by goatandsheep** [comment]
that's pretty awesome actually. The only thing is- this will be a breaking change. Do you think we should do both for now? As in, duplicate functionality temporarily with the new terms and then remove the white/black terms later?

**Comment by caiangums** [comment]
The idea is exactly a breaking change and possibly, be merged at a future release! 😄 

Thanks for accepting! 🙏
