### ISSUE TITLE
Multi-env doesn't change

### ISSUE THREAD

**Issue by KonstantinZhukovskij** [goatandsheep/react-native-dotenv#197]
Multi-env doesn't change. I **_always get variables from .env.development_**, most likely because this file is the first in the folder. I have the folder with 3 files: `.env.development .env.staging .env.production`. I've tried cleaning, reinstalling, and many more options, but nothing seems to work.

**My npm scripts:** 
```
"start:development": "NODE_ENV=development npx react-native start --reset-cache",
"start:staging": "NODE_ENV=staging npx react-native start --reset-cache",
"start:production": "NODE_ENV=production npx react-native start --reset-cache",
```

**I also use the next script:**

`"babel-clear": "rimraf node_modules/.cache/babel-loader/*,"`

**My babel config:**
```
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    [
      'module:react-native-dotenv',
      {
        moduleName: '@env',
        path: './config/.env',
        blocklist: null,
        allowlist: null,
        safe: false,
        allowUndefined: true,
      },
    ],
  ],
};
```

**In my file index.js** 

`import { URL } from '@env';`

**"react": "17.0.1",
"react-native": "0.64.1",
"react-native-dotenv": "^3.0.0",**

**Comment by goatandsheep** [comment]
How are you setting which environment you're using for your server? Are you using node_env? App_env? Setting it in your configs? Let's figure this out.

**Comment by KonstantinZhukovskij** [comment]
Updated. Please see in my question

**Comment by KonstantinZhukovskij** [comment]
I understand correctly that **NODE_ENV** indicates which file to use?

**Comment by goatandsheep** [comment]
Try applying the environment setting to your run script instead and let me know what happens

**Comment by KonstantinZhukovskij** [comment]
Could you give me an example?

**Comment by goatandsheep** [comment]
Sorry for the delay. I'm just doing a bit of research into the problem

**Comment by KonstantinZhukovskij** [comment]
Did you manage to reproduce it?

**Comment by goatandsheep** [comment]
Working on it here https://github.com/goatandsheep/react-native-dotenv-metro-demo

**Comment by KonstantinZhukovskij** [comment]
Also tell me please, can I get a variable **NODE_ENV** from other places? For example from gitlab CI?

**Comment by goatandsheep** [comment]
so I did find a bug actually. On gitlab CI my recommendation would be to do the same thing, which is run `NODE_ENV=test` staging isn't recommended but might work.

**Comment by goatandsheep** [comment]
will be fixed in [`v3.1.1`](https://www.npmjs.com/package/react-native-dotenv/v/3.1.1)

**Comment by goatandsheep** [comment]
@KonstantinZhukovskij if this change helps you, I request if you can make a donation, please do

**Comment by KonstantinZhukovskij** [comment]
@goatandsheep  I updated and it still doesn't work. Where exactly are you specifying **NODE_ENV**?

**Comment by KonstantinZhukovskij** [comment]
I updated and it works great. Thank you very much for your work.

**Comment by KonstantinZhukovskij** [comment]
@goatandsheep  I asked yesterday about whether I can set the **NODE_ENV** constant from other places, for example, from gitlab CI? Now I tried to build a test assembly and got a production environment everywhere. Could this be a library problem? What are the ways to create a constant **NODE_ENV**?

**Comment by goatandsheep** [comment]
That's bizarre! In test, you should get test. I don't think I know what you mean by set node_env everywhere. Can you please expand on that?

**Comment by KonstantinZhukovskij** [comment]
This is part of my code inside the gitlab CI. I am trying to understand whether it is possible to indicate the environment in this way?
```
firebase (stage):
  extends: .app-deploy
  stage: staging
  environment:
    name: stage
  variables:
    BUILD_DESTINATION: 'firebase'
    APP_IDENTIFIER: 'myID'
    NODE_ENV: 'stage'
```

**Comment by goatandsheep** [comment]
So the module should support reading the global NODE_ENV. However, I haven't tested it in this way yet. Also, for adding process.env variables into the mix, that is also in a pending PR. Go take a look if you're interested #191

If you want "staging", don't use "stage". Also, if you're not using test, development, or production, you're in experimental territory that I do not advise on a tight timeline.

**Comment by KonstantinZhukovskij** [comment]
> If you want "staging", don't use "stage".

What do you mean?

**Comment by goatandsheep** [comment]
Sorry about that message that was sent from my phone. Let me expand:

Disclaimer: I haven't used firebase config, I just saw:
```yaml
  environment:
    name: stage
```
so I assumed that it would use `.env.stage`? My apologies if I'm wrong.

I also don't know if this works, but I haven't tried:
```yaml
  variables:
    NODE_ENV: 'staging'
```
I recommend you set `verbose: true` (new option!) to see what value of env is being loaded.

And regarding
```yaml
  variables:
    BUILD_DESTINATION: 'firebase'
    APP_IDENTIFIER: 'myID'
```
These will only load if #191 is merged

**Comment by KonstantinZhukovskij** [comment]
@goatandsheep  Are you going to merge it?

**Comment by goatandsheep** [comment]
I'm waiting to see if I can get some support before I do as it's a major feature

**Comment by KonstantinZhukovskij** [comment]
@goatandsheep Could you create a new branch with the latest changes and #191 ?

**Comment by KonstantinZhukovskij** [comment]
@goatandsheep I made a patch with your changes #191 and tested it, but it still doesn't work. I am not getting data from my environment files, although I did get the NODE_ENV constant.
