### ISSUE TITLE
ENV variables are not loaded at runtime

### ISSUE THREAD

**Issue by vineetaparodkar** [goatandsheep/react-native-dotenv#199]
**Describe the bug**
ENV variables are not loaded at runtime. Old env variables are getting assigned in components and works if console logs are added.

**To Reproduce**
1. Added module in babel.config.js
```
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    ["module:react-native-dotenv"]
  ]
};
```
2. Added .env file in root directory with following values, Allowed THEME values -->theme1/theme2 DEFAULT_MODE=yes/no
```
THEME="theme1"
DEFAULT_MODE="yes"
```

3. Importing and using the env variables
```
import {THEME, DEFAULT_MODE} from "@env";
const AuthStack = createStackNavigator({
  Welcome: {
    screen: Welcome,
    navigationOptions: {
      title: 'APP NAME',
      headerShown: DEFAULT_MODE == "yes" ? true : false,
    }
  }})
```
4. Scripts updated in package.json
`"cc": "rimraf node_modules/.cache/babel-loader/*,",
"android": "npm run cc && react-native run-android",`

**Expected behavior**
Above code should work after changing THEME="theme2" & DEFAULT_MODE="no" and rebuilding app using `npm run android` and headerShown value should be false

** Error**
Above code still points to DEFAULT_MODE="yes" and works i.e. headerShown value updates to false only if there is console statement after import in every file. i.e
`import {THEME, DEFAULT_MODE} from "@env";
console.log("THEME CHECK",THEME, DEFAULT_MODE);
`

**React native version used:**
  "react": "16.13.1",
  "react-native": "0.63.3",

**Comment by goatandsheep** [comment]
My guess is that babel recompiles the file when you make the change of adding the console.log . I don't know why but I advise you try to invalidate the cache in your babel config https://github.com/goatandsheep/react-native-dotenv-metro-demo/blob/c0daeebe35a87c524eb88803e19f445d6d6956d4/babel.config.js#L2

**Comment by Ryanjso** [comment]
has anyone figured out a more elegant solution to this?

**Comment by goatandsheep** [comment]
I'm working on using a new Babel feature that came out this year but it has not been widely used so documentation has been challenging to follow. Fix should be in next release, tracked in #75

**Comment by Thebenjamist** [comment]
I just solved the issue, need to run yarn start --reset-cache, then it runs like a dream

**Comment by goatandsheep** [comment]
Hi @Ryanjso this ticket is closed because I haven't been able to reproduce it since recent changes. Make sure your Babel version is up to date or if you're using Expo that you're using the latest version of that or if you're using something else that is forcing the version of Babel down that you use package resolutions
