### ISSUE TITLE
Building a release with a specific environement file

### ISSUE THREAD

**Issue by ous24** [goatandsheep/react-native-dotenv#200]
i can't figure a way to build a release with my .env.staging , the release always use the .env.production file

**Comment by goatandsheep** [comment]
You will need to configure your signing config for each of your environments
https://reactnative.dev/docs/signed-apk-android#adding-signing-config-to-your-apps-gradle-config

**Comment by simonkarman** [comment]
@goatandsheep Where in the sign config can you specify the name of the environment it should use?

**Comment by v4irajvimu** [comment]
> i can't figure a way to build a release with my .env.staging , the release always use the .env.production file

did you find a way?

**Comment by goatandsheep** [comment]
I will review this ticket

**Comment by goatandsheep** [comment]
I will review this ticket but likely I'll recommend setting `NODE_ENV` if you're not just using development and production i.e. debug and release respectively and using the dev flag. Otherwise APP_ENV for everything else.

**Comment by rodgomesc** [comment]
@ous24 i'm modified the "Start Package" script in "Build Phases"  and it's working for me, just added 

```sh
# react-native-dot-env
if [ "$CONFIGURATION" = "Staging" ]; then
  export APP_ENV=stag
elif [ "$CONFIGURATION" = "Release" ]; then
  export APP_ENV=prod
elif [ "$CONFIGURATION" = "Debug" ]; then
  export APP_ENV=dev
fi
```

<img src="https://i.imgur.com/5ckPrsA.png" />
