### ISSUE TITLE
Feature Request: Load ENV variables in native projects

### ISSUE THREAD

**Issue by Qwin** [goatandsheep/react-native-dotenv#207]
Hi,

I am not sure if this is already possible, but I couldn't find anything about it. Right now to have the environment variables accessible from the iOS or Android project I would need to create a bridge that passes these values along.

Was wondering if we could implement something to allow access to the environment variables from the native projects? 

Thanks,
Robert

**Comment by andersonaddo** [comment]
This is pretty much a solved problem with https://www.npmjs.com/package/react-native-ultimate-config

**Comment by goatandsheep** [comment]
@Qwin I'm not really sure how that would work to be honest. My best guess is to follow the other suggestion here by @andersonaddo
