### ISSUE TITLE
Setting the right environment for development and release builds

### ISSUE THREAD

**Issue by snab88** [goatandsheep/react-native-dotenv#209]
I am trying to use `.env.development` and `.env.production` based off of NODE_ENV. We use App center to generate release builds. The environment always defaults to `.env.development` when I set NODE_ENV to production. 

Steps I do is as follows:
```
NODE_ENV=production
react-native start --reset-cache
react-native run-ios
```

**Comment by goatandsheep** [comment]
In my experience, it works better to set the environment variable on the same line as your server. What operating system are you on?

**Comment by snab88** [comment]
> In my experience, it works better to set the environment variable on the same line as your server. What operating system are you on?

Thanks for your reply. Its run in App center VMs which are macOS for react native.

**Comment by goatandsheep** [comment]
Try

```shell
> NODE_ENV=production react-native start --reset-cache
```

Instead of

```shell
> NODE_ENV=production
> react-native start --reset-cache
`

**Comment by snab88** [comment]
> Try
> 
> ```shell
> > NODE_ENV=production react-native start --reset-cache
> ```
> 
> Instead of
> 
> ```shell
> > NODE_ENV=production
> > react-native start --reset-cache
> ```

It works like that if I try locally. But the issue is that on a remote VM the metro bundler starts automatically before build so I wont have much control over what passed in the command

**Comment by goatandsheep** [comment]
okay I understand now. this is a common issue. You'll need to check out custom signing of your app as well as using variant / configuration / bundle options addressed in the wiki https://github.com/goatandsheep/react-native-dotenv/wiki/Multi-env-troubleshooting#react-native-cli

Let me know if this works

**Comment by JameDodgers** [comment]
> okay I understand now. this is a common issue. You'll need to check out custom signing of your app as well as using variant / configuration / bundle options addressed in the wiki https://github.com/goatandsheep/react-native-dotenv/wiki/Multi-env-troubleshooting#react-native-cli
> 
> Let me know if this works

Could you give me an example on how to do it? I was thinking in setup different values for NODE_ENV based on which buildType I'm assembling, but I don't know very much about gradle and everything I tried until now failed 😔
