### ISSUE TITLE
Add support for multi-env local files

### ISSUE THREAD

**Issue by Samhenry97** [goatandsheep/react-native-dotenv#210]
- [x] Tried the troubleshooting Wiki
- [x] Followed the migration Wiki

**Describe the bug**
This library does not work with multi-env local files, like `.env.development.local`. I looked at the code, and it's missing those cases in safe and regular mode. Could we please add that? It should be a simple change - I'm willing to open a PR if it's easier for you.

**To Reproduce**
Create `.env.development` and `.env.development.local` files, both with the same variable. In practice, `dotenv-flow` will choose the local version. However, this library only loads the non-local version.

**Comment by goatandsheep** [comment]
do you think we should just move to the `dotenv-flow` library from `dotenv`?

**Comment by Samhenry97** [comment]
That certainly seems like it could be a good solution. I think either way would work - if we don't move to that library, we can easily reproduce its behavior with just a few lines of code.

**Comment by goatandsheep** [comment]
Actually you're probably right. It may be difficult to deal with the environment variable values. If you want to create a branch I'll merge it in. I'm a bit swamped right now

**Comment by Samhenry97** [comment]
@goatandsheep the pull request is ready.
