### ISSUE TITLE
APP_ENV breaks builds that already use that environment variable

### ISSUE THREAD

**Issue by bfricka** [goatandsheep/react-native-dotenv#219]
- [x] Tried the troubleshooting Wiki
- [x] Followed the migration Wiki

**Describe the bug**
The title basically says it. The addition of the `APP_ENV` override is a breaking change for those of us who already had that variable defined for other purposes.

**Expected behavior**
I should have a way of overriding this variable if I don't want to use it or want to use another variable.

I've already created a fix for this, so I'm opening this issue because the template wanted me to do so before opening a PR.

**Comment by bfricka** [comment]
Hello there! It's been several days since I opened this, and I think it's a pretty straightforward issue and PR. Anything I can do to help this move forward? Thank you.

**Comment by goatandsheep** [comment]
sorry! I was AFK for a few months. I will be reviewing it and probably merging it within the next week

**Comment by bfricka** [comment]
Baaaahh

**Comment by goatandsheep** [comment]
okay I'm checking it now!!

**Comment by goatandsheep** [comment]
To be honest, I think `APP_ENV` should still be used even if you're already using it. It's better to be consistent with a standard. However, I won't be surprised if you're not the only one who wants this. I want to continue to label it as an experimental feature available as a backup in the README

**Comment by goatandsheep** [comment]
if you're okay with that, I'll merge the changes in, add the "fix", then tag you and if you're okay with that, I'll release the next version?

**Comment by goatandsheep** [comment]
I'll do release tomorrow

**Comment by bfricka** [comment]
In our case, we can't use `APP_ENV` because the enum that we use has different values from those accepted by dotenv.  At some point I might refactor this to use something else, but it's pretty consistent across our projects. I'm fine with however you want to release. Thanks.

**Comment by goatandsheep** [comment]
okay! with that, we can safely close this :)
