### ISSUE TITLE
ENOENT: no such file or directory, rename .react-native-dotenv.DELETE' npm ERR! enoent This is related to npm not being able to find a file

### ISSUE THREAD

**Issue by talaikis** [goatandsheep/react-native-dotenv#223]
- [x] Asked question in discussions
- [x] Tried the troubleshooting Wiki
- [x] Followed the migration Wiki

**Describe the bug**

When installing:

```
ENOENT: no such file or directory, rename ....\node_modules\.react-native-dotenv.DELETE' npm ERR! enoent This is related to npm not being able to find a file
```

**To Reproduce**

1. `npm i react-native-dotenv`

**Expected behavior**

Installs w/o problems.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: latest beta

**Comment by goatandsheep** [comment]
This is similar to this issue: https://github.com/npm/npm/issues/17444 let me know if the solutions there help you

**Comment by talaikis** [comment]
> This is similar to this issue: [npm/npm#17444](https://github.com/npm/npm/issues/17444) let me know if the solutions there help you

It does not, I went with yarn, so this seems is npm issue.
