### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by priyankar-navsoft** [goatandsheep/react-native-dotenv#23]
react-native-dotenv/index.js:9
  } catch {
          ^
SyntaxError: Unexpected token {

This error I am getting. What can be the cause?

**Comment by goatandsheep** [comment]
So this is explained in [this stackoverflow article](https://stackoverflow.com/a/56001361). I thought we could be clever and take advantage of the feature, but it is not supported by many older browsers. What I'll do is add a verbose mode that will spit out the errors conditionally so we can re-add the `err`:

```
} catch (err) {
  if (verbose) {
    console.error(err)
  }
  return {}
}
```
without the linter complaining about not using the `err`

**Comment by goatandsheep** [comment]
Thank you for opening this, @priyankar-navsoft let me know if the latest release solves this issue.
