### ISSUE TITLE
Main module is could not found your project

### ISSUE THREAD

**Issue by 02mk** [goatandsheep/react-native-dotenv#242]
- [ ] Asked question in discussions
- [x] Tried the troubleshooting Wiki
- [x] Followed the migration Wiki

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
![Screenshot_20211018-082603_Expo Go](https://user-images.githubusercontent.com/92702766/137662335-619ea594-bc17-48ad-b27b-6baa761318e0.jpg)

**Comment by goatandsheep** [comment]
Hi @02mk I did not see your question in discussions, but this looks like a familiar error. Are you sure you tried the troubleshooting wiki? It seems it may have been installed incorrectly. For most applications, this should be installed under dev dependencies as should babel
