### ISSUE TITLE
Feature request: Export function for programmatically loading .env files

### ISSUE THREAD

**Issue by hrastnik** [goatandsheep/react-native-dotenv#253]
What I'm trying to achieve:
I would like to use environment variables to control whether some babel plugins will be enabled. Namely - I want to include `babel-plugin-transform-remove-console` when the env variable `DISABLE_LOGGING` is set to `true`. This variable is configured in my `.env.dev` file.
I'm trying to achieve this by reading the value of the `DISABLE_LOGGING` env variable in my `babel.config.js` config, but
in order to access the variable through `process.env.DISABLE_LOGGING`, I have to first load the `react-native-dotenv` babel plugin.

Solution:
It would be nice if `react-native-dotenv` exported the config function similar to the `dotenv` package which can be used like so `require('dotenv').config()`.

I have been able to achieve this effect using this code, but it's undocumented and feels kind of hacky.

```js
const dotenv = require("react-native-dotenv")({});
dotenv.pre();
```

Is it possible to extract the configuration function and export it separately?

**Comment by goatandsheep** [comment]
Try using dotenv-flow

**Comment by goatandsheep** [comment]
or try using `process.env`?

**Comment by haelsisy** [comment]
How did you manage to do it?
