### ISSUE TITLE
Environment variables are not getting updated

### ISSUE THREAD

**Issue by raahuldaahaal** [goatandsheep/react-native-dotenv#254]
**I am using expo ~43.0.0**
The package reads the old value even if the server is re-started.
Tried all the solutions described in the [similar issue](https://github.com/goatandsheep/react-native-dotenv/issues/75). Didn't help.

**Workaround (not ideal)**
If I change the `App.js` file(I've imported env. variables here), the variables do get updated. 
But, why should we change the file?

I'm not sure if this is the issue with `react-native-dotenv` package or, `expo`.

**Comment by Coci0AlexMeew** [comment]
I just had a similar issue. I ran the following cmd to fix it:

`rm -rf $TMPDIR/metro-* && rm -rf $TMPDIR/haste-map-* yarn cache clean`

**Comment by goatandsheep** [comment]
thank you @Coci0AlexMeew ! I have also reopened #75 so I'm marking this as a duplicate
