### ISSUE TITLE
It is possible to import an env variable and use it in build.gradle?

### ISSUE THREAD

**Issue by catarinaguerreiro** [goatandsheep/react-native-dotenv#272]
- [x] Asked question in discussions
- [x] Tried the troubleshooting Wiki
- [x] Followed the migration Wiki

I am trying to use and env variable in the build.gradle file, but without success. 
I tried somethings like this:
`System.getenv('HOME')`

Can someone help me? 
Thank you :)

**Comment by goatandsheep** [comment]
no this is just for with Javascript :( you'll have to use react-native-config
