### ISSUE TITLE
How to build release apk with env.development

### ISSUE THREAD

**Issue by quocbaovu15101996** [goatandsheep/react-native-dotenv#279]
When I build the release file .apk in android. Env using the default is env.production, how can I build release .apk with env. development

**Comment by goatandsheep** [comment]
You'll need to sign it in development mode
https://reactnative.dev/docs/signed-apk-android#adding-signing-config-to-your-apps-gradle-config

**Comment by lnwanghao** [comment]
> You'll need to sign it in development variant https://reactnative.dev/docs/signed-apk-android#adding-signing-config-to-your-apps-gradle-config

I'm a little confused.
Is there any example that can achieve this?
