### ISSUE TITLE
[Feature request] Support react-native-web

### ISSUE THREAD

**Issue by phathuynh5519** [goatandsheep/react-native-dotenv#310]
Folks, we love your work, please help support this module for react-native-web sourcebase, we believe that your work will be recognized both on react-native and cross-stack communities, RNW is now the most prominent one in industrial ICT projects
Reference:
1. [https://github.com/necolas/react-native-web](https://github.com/necolas/react-native-web) (400K+ sourcebase worldwide)
2. [https://github.com/vemarav/react-native-web-typescript-template](https://github.com/vemarav/react-native-web-typescript-template)
Cheers,

**Comment by goatandsheep** [comment]
Hi @phathuynh5519 thank you! Are you facing any issues supporting web?

**Comment by phathuynh5519** [comment]
> Hi @phathuynh5519 thank you! Are you facing any issues supporting web?
Yep Dear, would u please support us, we tried uninstall node_modules folder and reinstall npm
```
TS2307: Cannot find module '@env' or its corresponding type declarations.
    16 | import {Lookup} from './screens/Lookup';
    17 | import Realm from 'realm';
  > 18 | import {email, password, realmID} from "@env";
       |                                                  ^^^^^^
    19 | import {getCurrentUser, addCurrentUser} from './constants/Realm';
    20 | const Tab = createBottomTabNavigator();
    21 |
```
```
  Binaries:
    Node: 16.13.2 - D:\Program Files\nodejs\node.EXE      
    Yarn: 1.22.4 - D:\Roaming\npm\yarn.CMD
    npm: 6.14.5 - D:\Roaming\npm\npm.CMD
```

**Comment by goatandsheep** [comment]
Oh this is a typescript issue. Can you try changing `moduleName` to "react-native-dotenv" and use "react-native-dotenv" instead of "@env" ?
