### ISSUE TITLE
Unable to resolve module `fs`

### ISSUE THREAD

**Issue by twinedo** [goatandsheep/react-native-dotenv#32]
I have issue like this:

error: Error: Unable to resolve module `fs` from `node_modules/react-native-dotenv/index.js`: fs could not be found within the project.

somebody can help???

**Comment by goatandsheep** [comment]
Seems related to [this issue](https://github.com/tusbar/babel-plugin-dotenv-import/issues/8). Do you think your babel is configured properly?

**Comment by twom** [comment]
@goatandsheep  and @twinedo 
see https://github.com/goatandsheep/react-native-dotenv/issues/20

This seems to stem from not renaming the import from 'react-native-dotenv' to '@env'

Maybe something to put in the migration guide or even a quick FAQ on the Readme.

**Comment by twinedo** [comment]
Thank you for your response. And sorry for super late response.
I have solve this issue by install module fs, then setup babel.config.js like read.md.. 
Thank you all 🙏

**Comment by goatandsheep** [comment]
@twinedo awesome! I'm so glad we were able to resolve this. You said you installed fs as an additional module? As in you used the fs built into node or a different npm module?

**Comment by twinedo** [comment]
i use yarn. when i check folder node_modules, there is no fs module. I don't why. So i install it 😁

**Comment by goatandsheep** [comment]
Well I'm happy it worked for you. [fs](https://www.npmjs.com/package/fs) is an empty module 🤡 I'm going to close this. let me know if I need to reopen.

**Comment by cengit** [comment]
I had same issue after upgrade react-native-dotenv. 
solution: make sure all import { xxx } from 'react-native-dotenv'; change to import { xxx } from '**@env'**;

**Comment by stevus** [comment]
Yea too bad this isn't documented properly. It's misleading to think we've got an option to not set the modulename.

**Comment by stevus** [comment]
listing this as a dev dependency does nothing to resolve the issue as stated in #20

**Comment by goatandsheep** [comment]
Feel free to open a PR if you have any documentation suggestions. I update the docs every few months including all suggestions. Saying it's bad unfortunately doesn't help. This is an old ticket so please continue at #392 . Locking.
