### ISSUE TITLE
Destructing `process.env`

### ISSUE THREAD

**Issue by row248-hola** [goatandsheep/react-native-dotenv#323]
- [ ] Asked question in discussions
- [x] Tried the troubleshooting Wiki
- [ ] Followed the migration Wiki

**Describe the bug**
Env variables set from destructing `process.env` is not processed by this package

**To Reproduce**
Access variables from `.env` file via this pattern:
```js
const {var1, var2} = process.env;
```

**Expected behavior**
`var1` and `var2` was replaced by value from .env if there is any

**Comment by goatandsheep** [comment]
can you explain the issue a bit more? When is this feature needed? Do you have any code examples?
