### ISSUE TITLE
Error: Unable to resolve module `fs` from `dotenv`

### ISSUE THREAD

**Issue by nicodes** [goatandsheep/react-native-dotenv#332]
Hello, I followed the steps to install `v3.3.1` to a fresh `expo v45.0.0` project and I am getting a build error. I have configured my `babel.config.js` as the instructions show, and used the `@env` import. I looked through `yarn.lock` and found this package has a dependency of `dotenv ^10.0.0`, perhaps this dependency is the issue? Build error below:
```
iOS Bundling failed 127ms
Unable to resolve module fs from /.../app/node_modules/dotenv/lib/main.js: fs could not be found within the project or in these directories:
  node_modules
  22 | */
  23 |
> 24 | const fs = require('fs')
     |                     ^
  25 | const path = require('path')
  26 | const os = require('os')
 ```

**Comment by nicodes** [comment]
Never mind, solved my issues with a sip of coffee 🤪

**Comment by robertclarkson** [comment]
Can I ask how did you solve it? Thank you

**Comment by pdavid0** [comment]
solved it with 
`yarn start --clear`
 to clear the metro cache

**Comment by CodingMeSwiftly** [comment]
> Never mind, solved my issues with a sip of coffee 🤪

A special place in hell is reserved for people like you.

**Comment by goatandsheep** [comment]
make sure to install as dev dependency only!
