### ISSUE TITLE
.env overrides .env.xxx

### ISSUE THREAD

**Issue by tobydeh** [goatandsheep/react-native-dotenv#348]
My understanding is that .env should be overridden by .env.xxx which it does when using safe mode, but when safe is set to false the order in which dotenv.config is called should be reversed.

Currently the order in which the files are loaded are: modeLocalFilePath, modeFilePath, localFilePath, path
This means that modeLocalFilePath is overridden by modeFilePath which is overridden by localFilePath which is overridden by path

```
dotenv.config({
      path: modeLocalFilePath,
      silent: true,
    })
    dotenv.config({
      path: modeFilePath,
      silent: true,
    })
    dotenv.config({
      path: localFilePath,
      silent: true,
    })
    dotenv.config({
      path: options.path,
    })
```

Should the order not be: path, localFilePath, modeFilePath, modelLocalFilePath?
This means that path is overridden by localFilePath which is overridden by modeFilePath which is overridden by modelLocalFilePath

```
dotenv.config({
      path: options.path,
    })
    dotenv.config({
      path: localFilePath,
      silent: true,
    })
    dotenv.config({
      path: modeFilePath,
      silent: true,
    })
    dotenv.config({
      path: modelLocalFilePath,
      silent: true,
    })
```

**Comment by goatandsheep** [comment]
I definitely need to fix this!!

**Comment by goatandsheep** [comment]
> [The order should be inversed as once defined it won't look elsewhere, which is a bit controversial](https://github.com/motdotla/dotenv/issues/256#issuecomment-598676663)

There are a few issues however, which I will fix

**Comment by goatandsheep** [comment]
note this will be released later

**Comment by tobydeh** [comment]
Hi, Thanks for taking a look. I'm not convinced that the order should be inverted, I think the following test proves that to be incorrect (the env value from .local is overridden).

.env
```
SOME_VALUE='from .env'
```
.env.local
```
SOME_VALUE='from .env.local'
```
```
const dotenv = require('dotenv')

dotenv.config({
  path: '.env.local',
  silent: true,
})
dotenv.config({
  path: '.env',
  silent: true,
})

console.log(process.env) // SOME_VALUE: 'from .env'
```

**Comment by tobydeh** [comment]
Ignore my previous comment - the problem seems to be related to the zsh dotenv plugin on my machine, when i disable the plugin the inverted behaviour works as expected.

Thanks again.
