### ISSUE TITLE
Cannot get env variables in rn 0.69

### ISSUE THREAD

**Issue by elirangoshen** [goatandsheep/react-native-dotenv#354]
- [x] Asked question in discussions
- [x] Tried the troubleshooting Wiki
- [x] Followed the migration Wiki

**Describe the bug**
im getting undefined variables in rn 0.69

**To Reproduce**
1. upgrade to rn 0.69
2. set env variables
3. it gets undefined

**Expected behavior**
that should work

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Iphone 13
 - OS: iOs 15.5

**Additional context**
my babel config file : 

```
const presets = ['module:metro-react-native-babel-preset']
const plugins = ['@babel/plugin-proposal-export-namespace-from']

plugins.push([
  'module-resolver',
  {
    root: ['./src'],
    extensions: ['.js', '.json'],
    alias: {
      '@': './src',
    },
  },
  'react-native-reanimated/plugin',
])

plugins.push([
  'module:react-native-dotenv',
  {
    envName: 'APP_ENV',
    moduleName: 'react-native-dotenv',
    path: '.env',
    safe: false,
    allowUndefined: true,
    verbose: false,
  },
])

module.exports = {
  presets,
  plugins,
}
```

how i try to import it : 

```
import {
  API_BASE_URL,
  CONTENTFUL_ACCESS_TOKEN,
  CONTENTFUL_BASE_URL,
} from 'react-native-dotenv'
```

**Comment by AlexCernik** [comment]
same on RN 70.1

**Comment by hsib19** [comment]
add <b>babel.config.js</b>

<pre>

plugins: [
    [
      "module:react-native-dotenv",
      {
        envName: "APP_ENV",
        moduleName: "@env",
        path: ".env"
      }
    ]
  ]

</pre>

**Comment by goatandsheep** [comment]
huh...I'm working on debugging some issues with the Babel team and I'm hoping it resolves a bunch of these, but i will also experiment shortly

**Comment by danidaryaweesh** [comment]
Is this still an issue?

**Comment by goatandsheep** [comment]
I'm not seeing the issue to be honest, but i'm assuming it's a caching issue

**Comment by goatandsheep** [comment]
Can you try again with latest version?

**Comment by dinumihnea** [comment]
From the documentation is not clear at which moment the env vars get populated.

If you're trying to use the env var at the top level in a file (e.g. right after imports), the value will come up as `undefined`. 
Is there a specific rule with that while using this library?

**Comment by goatandsheep** [comment]
Can you show me the error? I will create a how it works section I guess haha

**Comment by dinumihnea** [comment]
Thanks for the fast reply, so it turns out that the issue was the fact that I didn't restart the Metro server after configuring the plugin😅.  It works fine now.
