### ISSUE TITLE
Typescript example doesn't work in .ts files

### ISSUE THREAD

**Issue by christopherbauer** [goatandsheep/react-native-dotenv#382]
- [] Asked question in discussions (I'm posting a solution)
- [x] Tried the troubleshooting Wiki
- [] Followed the migration Wiki (New installation)

**Describe the bug**
When adding the library and following the description of how to use it for typescript, the module fails to load when running on the android emulator. However, changing the file extension from .ts => .tsx does fix it.

**To Reproduce**
1. Create a .ts file
2. Follow the installation and configuration methods for Typescript
3. Try to import some exported members from the .ts file
4. Android app crashes

**Expected behavior**
Android app does not crash

**Screenshots**
N/a

**Desktop (please complete the following information):**
 - OS: iOS M2
 - Browser Android
 - Version Latest

**Smartphone (please complete the following information):**
 - Device: Android emulator
 - OS: iOS latest
 - Browser N/a

**Additional context**
Changing the file extension to .tsx fixes the issue

**Comment by christopherbauer** [comment]
> Hey, thank you for opening this issue! 🙂 To boost priority on this issue and support open source please tip the team at https://issuehunt.io/r/goatandsheep/react-native-dotenv/issues/382

Shouldn't you be tipping me since I posted the solution? 🤔

**Comment by goatandsheep** [comment]
Unfortunately I'm broke right now but this is very very helpful! I will add this to the documentation. Thank you so much!

Maybe I need to reword the issue bot to indicate that I'm open to paid consulting to fix issues instead of what it currently says.

**Comment by christopherbauer** [comment]
> Unfortunately I'm broke right now but this is very very helpful! I will add this to the documentation. Thank you so much!

Sorry I just thought it was a funny reply, didn't mean anything by it :)

**Comment by goatandsheep** [comment]
So to be clear, the types definition file should be `.tsx`?
