### ISSUE TITLE
Capture Environment Variable For IOS and Android

### ISSUE THREAD

**Issue by CharlesPereira1** [goatandsheep/react-native-dotenv#386]
How do I capture the environment variable value and pass this info to the native IOS for dealings?

I know that in react-native-config it is possible to do:

```
// import header
#import "ReactNativeConfig.h"
// then read individual key like:
NSString *apiUrl = [ReactNativeConfig envFor:@"API_URL"];
// or just fetch the whole config
NSDictionary *config = [ReactNativeConfig env];

```
But would there be a way like this?

**Comment by goatandsheep** [comment]
Not that I know of unfortunately. This library is just a simple babel plugin for environment variables into JavaScript. If you know how to do it you're welcome to open a pr

**Comment by CharlesPereira1** [comment]
I solved it by installing react-native-config thanks
