### ISSUE TITLE
[BABEL]: Cannot find module 'node:fs'

### ISSUE THREAD

**Issue by iGroza** [goatandsheep/react-native-dotenv#392]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-dotenv@3.4.6` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-dotenv/index.js b/node_modules/react-native-dotenv/index.js
index 148baba..5086059 100644
--- a/node_modules/react-native-dotenv/index.js
+++ b/node_modules/react-native-dotenv/index.js
@@ -1,5 +1,5 @@
-const {readFileSync, statSync} = require('node:fs')
-const path = require('node:path')
+const {readFileSync, statSync} = require('fs')
+const path = require('path')
 const dotenv = require('dotenv')
 
 function parseDotenvFile(path, verbose = false) {
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by Muthu011** [comment]
I am also facing the same issue

**Comment by goatandsheep** [comment]
Hi I made this change recently on purpose. Please do not use this library as a production dependency. Use it as a dev dependency

**Comment by subhadeepquantiantech** [comment]
same issue

**Comment by goatandsheep** [comment]
Please confirm that this is a dev dependency not prod dependency

**Comment by goatandsheep** [comment]
Some folks here are saying that making it devDependency is not fixing it. I suppose it could be because of the recent change from fs to node:fs and path to node:path but I'm not sure why and I'm not sure if there's another answer we're overlooking

**Comment by goatandsheep** [comment]
Ok I have an idea now of what the issue might be. node:fs is a feature of node >18.x . Since LTS versions of 14.x and 16.x are still in maintenance, I will revert this as long as someone can identify that upgrading their node version fixes the issue. I will create a draft PR for now.

**Comment by ArtyEmsee** [comment]
I'm also seeing this on a new project-- node version is `18.12.1 LTS` and seeing the same error regardless of prod v dev dependency injection.

**Comment by knro** [comment]
Same issue here and it was installed as a DEV dependency.

**Comment by goatandsheep** [comment]
Ok I will reverse the change as it seems to be a bug not usage issue

**Comment by goatandsheep** [comment]
I have reverted this in 3.4.7 . Please let me know if the issue persists.

**Comment by MarcosSarges** [comment]
I'm using version 3.4.11 and during the bundle the code doesn't find the path

```
error: Error: Unable to resolve module path from <omitted>/node_modules/react-native-dotenv/index.js: path could not be found within the project or in these directories:
  node_modules
  1 | const fs = require('fs')
> 2 | const path = require('path')
    |                       ^
  3 | const dotenv = require('dotenv')
  4 |
  5 | function parseDotenvFile(path, verbose = false) {
    at ModuleResolver.resolveDependency (<omited>/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:138:15)
    at DependencyGraph.resolveDependency (<omited>/node_modules/metro/src/node-haste/DependencyGraph.js:231:43)
    at <omited>/node_modules/metro/src/lib/transformHelpers.js:156:21
    at resolveDependencies (<omited>/node_modules/metro/src/DeltaBundler/buildSubgraph.js:42:25)
    at visit (<omited>/node_modules/metro/src/DeltaBundler/buildSubgraph.js:83:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async visit (<omited>/node_modules/metro/src/DeltaBundler/buildSubgraph.js:92:5)
    at async Promise.all (index 2)
    at async visit (<omited>/node_modules/metro/src/DeltaBundler/buildSubgraph.js:92:5)
```

npx react-native info
```

System:
  OS: macOS 14.6.1
  CPU: (8) arm64 Apple M1
  Memory: 75.69 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.11.1
    path: ~/.nvm/versions/node/v20.11.1/bin/node
  Yarn:
    version: 3.6.4
    path: ~/.yarn/bin/yarn
  npm:
    version: 10.2.4
    path: ~/.nvm/versions/node/v20.11.1/bin/npm
  Watchman:
    version: 2024.07.08.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /<omitted>/.rvm/gems/ruby-2.7.5/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK:
    API Levels:
      - "21"
      - "27"
      - "28"
      - "29"
      - "30"
      - "31"
      - "32"
      - "33"
      - "34"
    Build Tools:
      - 28.0.3
      - 29.0.0
      - 29.0.2
      - 29.0.3
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 33.0.0
      - 34.0.0
      - 35.0.0
    System Images:
      - android-30 | Google Play ARM 64 v8a
      - android-31 | Google Play ARM 64 v8a
      - android-35 | Google Play ARM 64 v8a
    Android NDK: 21.3.6528147
IDEs:
  Android Studio: 2023.3 AI-233.14808.21.2331.11709847
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.11
    path: /<omitted>/.jenv/shims/javac
  Ruby:
    version: 2.7.5
    path: /<omitted>/.rvm/rubies/ruby-2.7.5/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.3
    wanted: 0.74.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

**Comment by goatandsheep** [comment]
@MarcosSarges can you verify you have installed as a dev dependency?

**Comment by devartwa** [comment]
@MarcosSarges same issue here.

@goatandsheep I've installed as dev dep, but still having the same error.

**Comment by MarcosSarges** [comment]
@devartwa  and @goatandsheep 

What worked for me was declaring "@env" and "envName" in babelconfig

```js
  [
      "module:react-native-dotenv",
      {
        envName: "APP_ENV",
        moduleName: "@env",
        path: ".env",
      },
    ],
```
I also downgraded to 3.4.7 (I saw in other issues that this version worked)

**Comment by goatandsheep** [comment]
@MarcosSarges downgrading helped? I gotta look into this 😬 but be prepared for some diagnostic questions

**Comment by MarcosSarges** [comment]
> @MarcosSarges downgrading helped? I gotta look into this 😬 but be prepared for some diagnostic questions

Honestly, I don't know if downgrading helped LMFO

I'll test the latest version.

**Comment by devartwa** [comment]
Guys, I’ve found a solution:

1. Add the dotenv library as a dev dependency.
2. Add these two properties: allowUndefined: false and safe: true.
3. Restart your project (clear the cache if possible).

Example:

`plugins: [['module:react-native-dotenv', { moduleName: 'react-native-dotenv', allowUndefined: false, safe: true }]]`

Give it a try and let me know if it helps!
