### ISSUE TITLE
error: Error: Unable to resolve module @env

### ISSUE THREAD

**Issue by maoryadin** [goatandsheep/react-native-dotenv#394]
No matter what I do, it's just not working.

babel.config.json:
```
{
    "presets": ["@babel/preset-react","module:metro-react-native-babel-preset"],
    "plugins": [
      ["module:react-native-dotenv", {
        "moduleName": "@env",
        "path": ".env",
        "safe": false,
        "allowUndefined": true
      }]
    ]
}

```

error:
```
error: Error: Unable to resolve module @env from /Users/maoryadin/spetz-git/project/src/constants/config.js: @env could not be found within the project or in these directories:
  node_modules
  ../../node_modules
  1 | import {AppColors, AppSizes, AppStyles} from '../theme';
  2 | import {Platform} from 'react-native';
> 3 | import {SERVER_URL, RATING_URL, ENV} from '@env';

```

I have a .env file that exists.

**Comment by goatandsheep** [comment]
Is the library installed as dev dependency?

**Comment by goatandsheep** [comment]
Also try using Babel.config.js and setting API.cache(false)

**Comment by maoryadin** [comment]
> Is the library installed as dev dependency?

yes, installed in devDependencies

**Comment by maoryadin** [comment]
> Also try using Babel.config.js and setting API.cache(false) You shouldn't need this but if you didn't update your Babel then this is a workaround

So as you suggested i am now using babel.config.js
i am getting different error:

[BABEL]: Cannot find module 'node:fs'

my react-native-dotenv version is 3.4.6 by the way.

**Comment by maoryadin** [comment]
Hey, i have successfully succeeded, i think adding import react before has fixes the issue, not sure but its work :)

**Comment by abiScript** [comment]
> Hey, i have successfully succeeded, i think adding import react before has fixes the issue, not sure but its work :)

Can confirm that adding the import for the env module **before** importing React worked for me as I had just run into the same issue.

**Comment by goatandsheep** [comment]
Hi tomorrow I will verify and I can update the docs to include this :)

**Comment by enzzoperez** [comment]
> Hey, i have successfully succeeded, i think adding import react before has fixes the issue, not sure but its work :)

Hi!, Im having the same issue, how is the fix that you used?, I have my `react import` in first line in my file where Im using the @env import, but doesnt work

**Comment by Narayen** [comment]
Hi, 

I had the same issue, while trying to import through `@env`. as suggested in the above comments, I tried importing React and it worked for me. 

I added the `import React from 'react';` at the first line.

**Comment by DeeDyPL** [comment]
> Hi,
> 
> I had the same issue, while trying to import through `@env`. as suggested in the above comments, I tried importing React and it worked for me.
> 
> I added the `import React from 'react';` at the first line.

Yes, it helped!

**Comment by TausifM** [comment]
> Is the library installed as dev dependency?

Yes

**Comment by goatandsheep** [comment]
Where should people import react?
