### ISSUE TITLE
Question | Which .env file is used during an eas update with Expo?

### ISSUE THREAD

**Issue by maoryadin** [goatandsheep/react-native-dotenv#396]
Which .env file is used during an eas update with Expo?

Is there a specific .env file that is used during an **eas update** with Expo, and if so, which one is it?

I have those env files:

.env.local
.env.development
.env.production

When using eas build, 
I do not encounter any problems because I am specifying the "env" key in my eas.json file for each profile.

**Comment by goatandsheep** [comment]
You need to put your environment variables as secrets onto the EAS platform

**Comment by goatandsheep** [comment]
Feel free to continue the discussion here https://github.com/goatandsheep/react-native-dotenv/discussions/388
