### ISSUE TITLE
🐛 .env file override order is slightly off compared to dotenv-flow

### ISSUE THREAD

**Issue by walkerdb** [goatandsheep/react-native-dotenv#397]
`dotenv-flow` [describes their override order as the following](https://github.com/kerimdzhanov/dotenv-flow#variables-overwritingpriority):

1. base `.env`
2. `.env.local`
3. `.env.[environment]`
4. `.env.[environment].local`
5. ...local environment variables

However this library's current override order is:

1. base `.env`
2. `.env.[environment]`
3. `.env.local`
4. `.env.[environment].local`
5. ...local environment variables

with 2 and 3 swapped compared to `dotenv-flow`. This order is defined by a series of object assignments here: https://github.com/goatandsheep/react-native-dotenv/blob/main/index.js#L93-L94

Can this be switched around to match `dotenv-flow`'s approach instead?

**Comment by goatandsheep** [comment]
That is bad and sloppy. I'll take a look

**Comment by elitenas** [comment]
I am still seeing this as an issue.

.env.development is taking priority over .env.local

**Comment by goatandsheep** [comment]
I will have to double check

**Comment by elitenas** [comment]
@goatandsheep .env.local takes priority over .env.production which is good. I am only seeing this issue between .env.local and .env.development

More info on order below:

https://create-react-app.dev/docs/adding-custom-environment-variables/#what-other-env-files-can-be-used

<img width="1326" alt="image" src="https://user-images.githubusercontent.com/50789023/219989523-180fef65-d629-4fc9-9bb8-8ed45546923c.png">

**Comment by goatandsheep** [comment]
Hi @elitenas can you send me your babel configuration / reproduction details?

**Comment by elitenas** [comment]
Here is a barebone repro project: https://drive.google.com/file/d/1U9sGA3cvVLKW6caPdSVvip79u5ByH7E-/view?usp=sharing

In the repro project, i am outputting the value of API_URL. I am seeing the value show up as http://testing.com instead of http://testing222.com.

even though .env.local should have higher priority

**Comment by goatandsheep** [comment]
Hi @elitenas I'm closing this as this is an old issue and the new issue is #415
