### ISSUE TITLE
Expo throwing fs not found error.

### ISSUE THREAD

**Issue by Haseebshah936** [goatandsheep/react-native-dotenv#408]
**Error Statement:** 

The package at "node_modules/react-native-dotenv/index.js" attempted to import the Node standard library module "fs".
It failed because the native React runtime does not include the Node standard library.

**Balblel.config**

```
module.exports = function (api) {
  api.cache(false);
  return {
    presets: ["babel-preset-expo"],
    env: {
      production: {
        plugins: [
          ["react-native-paper/babel"],
          [
            "module:react-native-dotenv",
            {
              moduleName: "react-native-dotenv",
              verbose: true,
            },
          ],
        ],
      },
    },
  };
};
```

**Environment:** 

Expo sdk ~47.0.12
React native 0.70.5
React 18.1.0

**Comment by goatandsheep** [comment]
Hi @Haseebshah936 I've transferred the ticket here from the expo test repo. Can you please verify that you have installed react-native-dotenv as a devdependency ?

**Comment by Haseebshah936** [comment]
@goatandsheep yes I installed it as a dependency. But for now I am not using it. Still if you need any help regrading testing I will be happy to help you ☺️.

**Comment by goatandsheep** [comment]
Thank you for the help! To be clear was it installed as a regular dependency or devdependency? It needs to be installed as a devdependency

**Comment by patrickpistor** [comment]
@goatandsheep Running into this issue as well with it installed as a dev dependency. Latest version of expo SDK

**Comment by goatandsheep** [comment]
@patrickpistor are you importing react-native-dotenv in your app? Expo will bundle all libraries that are imported whether or not they are installed as devDependency. Also if you are, can you verify that in your Babel that you have set your module name in your babel.config.js to "react-native-dotenv" so it is replaced by Babel with the env object?

**Comment by IM-Deane** [comment]
Hey there, I also encountered this error today in a fresh project while following the `README.md`.

## My setup:

### Imported it:
```typescript
// index.ts

import {
	REACT_NATIVE_SUPABASE_URL,
	REACT_NATIVE_SUPABASE_ANON_KEY,
} from "react-native-dotenv";
```

### My types file:
```typescript
// types/env.ds.tsx

declare module "react-native-dotenv" {
	export const REACT_NATIVE_SUPABASE_URL: string;
	export const REACT_NATIVE_SUPABASE_ANON_KEY: string;
}

const supabaseUrl = REACT_NATIVE_SUPABASE_URL;
const supabaseAnonKey = REACT_NATIVE_SUPABASE_ANON_KEY;
```

### My babel.config.js:

```javascript
module.exports = function (api) {
	api.cache(true);
	return {
		presets: ["babel-preset-expo"],
		plugins: [
			[
				"module:react-native-dotenv",
				{
					moduleName: "react-native-dotenv",
					path: ".env",
				},
			],
		],
	};
};
```


### Error encountered:
```sh
iOS Bundling failed 294ms
The package at "node_modules/react-native-dotenv/index.js" attempted to import the Node standard library module "fs".
It failed because the native React runtime does not include the Node standard library.
```

**Comment by goatandsheep** [comment]
Hi @IM-Deane can you please verify in your package.json that `react-native-dotenv` is a devDependency NOT a dependency? Otherwise setup looks fine.

**Comment by patrickpistor** [comment]
> @patrickpistor I stalked your profile and noticed this package.json has react-native-dotenv in the dependencies array not devDependencies https://github.com/Photure/PhotureEthGlobal/blob/master/package.json

@goatandsheep that project is dated, this is the one I am using the correct package in the correct place [https://github.com/patrickpistor/mixer](https://github.com/patrickpistor/mixer)

**Comment by patrickpistor** [comment]
I have an open bounty for $45 on Replit if anyone can figure this out: https://replit.com/bounties/@patrickpistor1/create-a-react-nativ

**Comment by goatandsheep** [comment]
I didn't see the error regarding `fs`
https://www.loom.com/share/20b80aa6ab1b4bfb922ce097a187937b
https://github.com/goatandsheep/mixer-bounty

**Comment by goatandsheep** [comment]
I didn't see the error regarding fs
https://www.loom.com/share/20b80aa6ab1b4bfb922ce097a187937b
https://github.com/goatandsheep/mixer-bounty

**Comment by goatandsheep** [comment]
also i have a second expo example here https://github.com/goatandsheep/react-native-dotenv-expo-test

**Comment by patrickpistor** [comment]
Thanks @goatandsheep That repo that you made worked. I can give you the bounty if you apply on Replit

**Comment by goatandsheep** [comment]
I've applied! :)

**Comment by goatandsheep** [comment]
thank you! I uploaded a replit :)
I realized you removed the yarn upgrades, so maybe it was the `esModuleInterop`. I will add that to the README
