### ISSUE TITLE
Add option to ignore process.env when on CI

### ISSUE THREAD

**Issue by goatandsheep** [goatandsheep/react-native-dotenv#410]
Originally opened by @lmcjt37

> My team found during an upgrade to react native, along with many other packages, that a change occurred that caused our `.env.test` to be ignored in favour of the environment variables injected via the CI. This appeared to only be the case when running `yarn test --coverage`.
>
> Interestingly, when changing the `coverageProvider` to "v8", the environment variables were correct. But that didn't solve all our issues and raised other significantly complex issues.

**Comment by goatandsheep** [comment]
What are you using `.env.test` for? Are you able to remove the environment variables from the CI settings? I don't think I'm understanding but I thought the whole thing about choosing the environment name through `ENV=` (or `APP_ENV=` if that doesn't work) is that you can choose which set of environment variables to go with, i.e. one for testing, one for CI, etc. Let me know what I'm not understanding.

Also are you running multiple tests in the same script? I wonder if this is a caching problem.

**Comment by lmcjt37** [comment]
The weird thing is that before the upgrade everything was working, the upgrade introduced a lot of breaking changes.

Our `.env.test` file is there specifically to inject variables for unit tests, and we load the file in specifically through babel.config. We found this issue only when running `yarn test --coverage`, so perhaps something in the environment changes specifically for Jest (since the update) when the coverage flag is set.

In our case we saw the CI environment variables taking precedence over the loaded `.env` file in the above scenario which caused our tests to fail.

Additionally, I had tested setting `APP_ENV` which didn't make a difference, and could see logging showing me the expected steps in your script were running through.

**Comment by goatandsheep** [comment]
What happens if you delete the CI environment variables? Are you able to do that without messing up the builds?

**Comment by lmcjt37** [comment]
We aren't able to remove the variables being overridden. These values are secrets hence the `.env.test` to replace just the necessary ones.

But, what you're asking about removing the value from the CI. That will allow the `.env.<ENVIRONMENT>` to work as expected. This is why I introduced the additional argument as it seemed a less invasive approach. If it's not used then everything carries on working as is.

**Comment by goatandsheep** [comment]
I think there's already a way to make sure that we don't import the local variables. Let me check

**Comment by goatandsheep** [comment]
Can you set the necessary variables to `undefined` in your `babel.config.js`? This will clear the values in `process.env`

**Comment by goatandsheep** [comment]
@lmcjt37 I am hesitant to add this not only because it encourages a bad practice but because your context implies you're likely using this library in a dangerous way. You should have `.env.test` in your `.gitignore` unless it is very generic settings. You should be setting your environment variables through the CI portal. If you know of a case where this happened because of unnecessary system environment variables taking priority, then we should collaborate on toggling system environment variables, but not for this context. This library is meant to emulate `dotenv-flow` for babel-specific projects and this is outside of that scope.

**Comment by lmcjt37** [comment]
I'm happy to close this.

We have since refactored our pipeline and context variables. So it's likely this isn't an issue any longer.

I will retest without our patch to confirm.

**Comment by skumhar** [comment]
@lmcjt37  I'm using API_URI from @env, and it correctly pulls the value from the .env file. All tests pass when I run yarn test, but when I run yarn test --coverage or in the CI/CD pipeline, I get a ReferenceError: API_URI is not defined.

**Comment by lmcjt37** [comment]
@skumhar Sorry, I can't remember enough about the issue we faced now.

This is the closed PR if that helps debug the issue https://github.com/goatandsheep/react-native-dotenv/pull/403/files

The other suggestion is to check what the value is when using `yarn test --coverage` locally to try and identify the flow
