### ISSUE TITLE
Env variables undefined with expo 48

### ISSUE THREAD

**Issue by elitenas** [goatandsheep/react-native-dotenv#415]
Hi,

After upgrading to expo 48, environment variables come undefined on the mobile app but work fine on react-native-web with expo.

I am using babel-loader 9.x.x with expo 48 due to expo 48 upgrading to webpack 5

I have tried `.env` `.env.local` `.env.production.local` and `.env.production` all are returning me undefined

**Comment by goatandsheep** [comment]
To test
- [ ] expo 48 with babel-loader 8.x.x

Tested and working

- [x] expo 48 with babel-loader 8.x.x

**Comment by goatandsheep** [comment]
this is my start script:

```json
"start:npx-dev": "NODE_ENV=development&& npx expo start --clear"
```

Other info on variants in expo:
* https://docs.expo.dev/build-reference/variants/
* [eas.json](https://docs.expo.dev/build/eas-json/#common-use-cases)

**Comment by goatandsheep** [comment]
if you're using another way to configure your NODE_ENV you're going to have to figure it out yourself

**Comment by goatandsheep** [comment]
[relevant](https://github.com/goatandsheep/react-native-dotenv/issues/397#issuecomment-1440167956)
