### ISSUE TITLE
Looking for backup collaborators

### ISSUE THREAD

**Issue by goatandsheep** [goatandsheep/react-native-dotenv#47]
I'm looking to find a backup collaborator. It's not a good thing when projects have only 1 collaborator. It's better for project longevity to have some redundancy.

**Comment by goatandsheep** [comment]
It's healthy to have many contributors for npm packages in case something happens to one. If you'd like to be a contributor let me know. For the state of the package, the best help would be to create a test snack app (issue #30).

**Comment by iagows** [comment]
I want to help :)
