### ISSUE TITLE
How to use with jest? ReferenceError: ENV_VARIABLE is not defined. 

### ISSUE THREAD

**Issue by ugglr** [goatandsheep/react-native-dotenv#59]
I'm running a react-native project with the typical usage, and getting an error while testing:

```
ReferenceError: ENV_VARIABLE is not defined.
```

`babel.config.js`
```js
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: ['module:react-native-dotenv'],
}
```

I use it like this: (for simplicity)

`function.js`
```js
import { SECRET_URL } from '@env'

export default = () => {
  return `${SECRET_URL}`
}

```

I add a test to my function: `function.test.js` and does something like this

```js
describe('testing my function', () => {
  it('should return correct url', () => {
   const foo = myFunction()
   expect(foo).toBe('whatever url I was expecting')
  }
 )
)
```

Do I need to mock things with jest or what's the workflow?

**Comment by tobiasbu** [comment]
+1 I'm in the same situation. Is there a way to use this lib with Jest?

**Comment by goatandsheep** [comment]
Take a look at how the library is doing it https://github.com/goatandsheep/react-native-dotenv/blob/53610ef83f82b9ea15f7973f160fe1e1b0a4e83c/__tests__/index.test.js#L43

essentially, just set the value of your value inside `process.env`. Let me know if that helps!

**Comment by goatandsheep** [comment]
I've now added a way to use `.env.test` as environment variables. Does that help?

**Comment by developerantoniosousa** [comment]
@goatandsheep I think it can help. But another way to do it would be a way to specify the file, like a way to provide the name of file that be executed that time.

**Comment by goatandsheep** [comment]
good point! you can do that in your `.babelrc`:

```json
{
    "env": {
        "test": {
            "plugins": [["module:react-native-dotenv", { "path": "/path/to/file" }]],
        }
    }
}
```

**Comment by developerantoniosousa** [comment]
But that process could be better. For example, through the variable that can set the file, because it's cool to determine it of a different way. It could open options, for example, to define a .env.test when the script of test to be executed, without the necessity of update always the path in babel configuration file.

**Comment by goatandsheep** [comment]
You can actually try both options now to see what works for you :) as of v2.4.0

**Comment by developerantoniosousa** [comment]
How can I do as I said before?

**Comment by goatandsheep** [comment]
I actually recommend if you want to do tests with different sets of variables, you just define them inline like how it's done in these Jest tests:
https://github.com/goatandsheep/react-native-dotenv/blob/a1542a7c1970a6141c80c56662dc0954ff85b7d2/__tests__/index.test.js#L43

Specifying multiple individual files will be very tricky and would change how the library operates completely.

You can even define a list of fakes, like in your `.env.test`:

```
SHOW_FEATURE_A_TEST_1=true
SHOW_FEATURE_A_TEST_2=false
SHOW_FEATURE_A=false
```

and then in jest before the test you say:

```javascript
process.env.SHOW_FEATURE_A = process.env.SHOW_FEATURE_A_TEST_1
```
and repeat for each test. What do you think about that?

**Comment by developerantoniosousa** [comment]
It seems nice!

I solve my problem as you said [before](https://github.com/goatandsheep/react-native-dotenv/issues/59#issuecomment-685038230), I was using an old version of library. I have done the update and the set up and now all works well. Thanks!

**Comment by ugglr** [comment]
I actually made a work around for this on my end so if @goatandsheep want's to close that's all good on my side, I'm still using the package so I will probably circle back if I run into issues 🤓

**Comment by goatandsheep** [comment]
@ugglr cool! can you show me a code snippet? maybe it can give me a better idea on what to improve

**Comment by marcorivm** [comment]
> But that process could be better. For example, through the variable that can set the file, because it's cool to determine it of a different way. It could open options, for example, to define a .env.test when the script of test to be executed, without the necessity of update always the path in babel configuration file.

You can do a lot on the babel config file take a look at https://babeljs.io/docs/en/configuration#javascript-configuration-files, why bake more functionality into the plugin when switching envs can be easily setup there. Another idea is when running your test script you can setup env variables for that run only via command line

**Comment by developerantoniosousa** [comment]
> > But that process could be better. For example, through the variable that can set the file, because it's cool to determine it of a different way. It could open options, for example, to define a .env.test when the script of test to be executed, without the necessity of update always the path in babel configuration file.
> 
> You can do a lot on the babel config file take a look at https://babeljs.io/docs/en/configuration#javascript-configuration-files, why bake more functionality into the plugin when switching envs can be easily setup there. Another idea is when running your test script you can setup env variables for that run only via command line

That's it @marcorivm.

I solved my problem using this solution, with Babel.

**Comment by leonardonelson91** [comment]
@goatandsheep Is there a way to programatically set the environment variables for dotenv in jest?

I'm trying to do something like:

`jest.mock('react-native-dotenv', () => ({
  VARIABLE1: 'value',
  VARIABLE2: 'value2',
}));`

Different tests might have different values for the same environment variables. If I have only a single source I can't have this flexibility.

**Comment by leonardonelson91** [comment]
@goatandsheep I tried [this](https://github.com/goatandsheep/react-native-dotenv/issues/59#issuecomment-685055901) but that did not work for me.

**Comment by goatandsheep** [comment]
@leonardonelson91 yes there's a new experimental feature with 2.5.0 that adds APP_ENV . Look at #97

**Comment by goatandsheep** [comment]
Some people are saying to follow the Android signing guide https://reactnative.dev/docs/signed-apk-android#adding-signing-config-to-your-apps-gradle-config

**Comment by ro-mgh** [comment]
Only this worked out for me: you could just simply add this variable to your jest.config.js.

module.exports = {
  ...
  globals: {
    ...
    ENV_VARIABLE: 'env_variable',
    ...
  },
  ...
};

**Comment by sarulathadurai** [comment]
For me the env variables are accessible while running test but while getting coverage the env variables are not loading creating 
`ReferenceError: ENV_VARIABLE is not defined.`

**Comment by goatandsheep** [comment]
Make sure to set `NODE_ENV` https://jestjs.io/docs/environment-variables

**Comment by andvalsol** [comment]
@sarulathadurai were you able to fix the issue?

**Comment by sarulathadurai** [comment]
> @sarulathadurai were you able to fix the issue?

To fix this don't import env variables as

import {ENV_VARIABLE} from @env

Instead use 

const env = process.env

and use env.ENV_VARIABLE wherever required. This way both tests and coverage are running properly

**Comment by ColeDre** [comment]
Was able to get this working using 
```
env: {
    'test': {
        plugins: [["module:react-native-dotenv", {
          path: `${api.env() ? 'api.' + api.env() : '.env'}`
        }]],
    }
}
```


In config

**Comment by jdbasophos** [comment]
this work to me
https://dev.to/darkmavis1980/how-to-mock-environmental-variables-with-jest-2j3c

**Comment by rafal-r** [comment]
@sarulathadurai @andvalsol 
It is also possible to get rid of those errors by the changing the coverage provider `--coverageProvider=v8`.
Unfortunately this may lead to bigger memory consumption and might require higher resources on your CI.

**Comment by santimuller** [comment]
@sarulathadurai with your solution worksl!

Another way: 
You could use the variables importing from react-native-dot-env: 

import {API_URL} from '@env';`
Added this instead:
`
import {API_URL} from 'react-native-dotenv';
`
It works well too.

**Comment by foloinfo** [comment]
I had the similar problem.
It was acting weirdly that it loads correctly once I `console.log` the loaded variables, it works completely fine in the development environment, but not in the test env.
It looks like calling the variable once will correctly load the env var, so I ended up doing like this.

```
import { ENV_VARIABLE } from @env
(() => {
  { ENV_VARIABLE }
})()
```

**Comment by dhenaotoro** [comment]
@foloinfo It's a good point what you mentioned, so if you reassign the `env` var to a `const` or `let` variable, it actually works as well:

```
import { REACT_NATIVE_APP_BACKEND_URL } from '@env';

const expectedEnv = REACT_NATIVE_APP_BACKEND_URL;
const urlUserBase = `${expectedEnv}/api/user`;
```

**Comment by adityadesai192k** [comment]
ReferenceError: AUTH_SERVICE_ISSUER is not defined

I'm getting this error where AUTH_SERVICE_ISSUER  is environment variable while testing my function. How can I resolve?
