### ISSUE TITLE
Autogenerate typescript typings file

### ISSUE THREAD

**Issue by goatandsheep** [goatandsheep/react-native-dotenv#62]
- Create a `types` folder in your project
- Inside that folder, create a `*.d.ts`file, say, `env.d.ts`
- in that file, declare a module as the following format:
```ts
declare module '@env' {
  export const API_BASE: string;
}
```
You should add all of your .env variables inside this module.

- Finally, add this folder into the `typeRoots` field in your `tsconfig.json` file:
```json
{
...
    "typeRoots": ["./src/types"],
...
}
```

_Originally posted by @ajaxjiang96 in https://github.com/goatandsheep/react-native-dotenv/issues/52#issuecomment-673218479_

**Comment by goatandsheep** [comment]
I think this can be based on the whitelist array

**Comment by goatandsheep** [comment]
I think we can keep this open

**Comment by FanchenBao** [comment]
I use the same concept to set up a stub `react-native-dotenv_v2.5.0.js` for use in `flow` typing:

```javascript
/**
 * @flow
 *
 * Flow stub for react-native-dotenv
 */

declare module '@env' {
  declare export var ENV: string;
  declare export var API_BASE: string;
  declare export var API_KEY: string;
  // other env variables
}
```
I use [`flow-typed`](https://github.com/flow-typed/flow-typed) to handle packages without official `flow` support. The `react-native-dotenv_v2.5.0.js` file is stored in the `flow-typed` directory.

**Comment by goatandsheep** [comment]
I also realized the following repo is messed up:

https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-native-dotenv

https://www.npmjs.com/package/@types/react-native-dotenv

**Comment by ericbaobao** [comment]
> I also realized the following repo is messed up:
> 
> https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-native-dotenv
> 
> https://www.npmjs.com/package/@types/react-native-dotenv

I don't want to open a new issue so I will just ask in here seem it's relevant
so first I added it to tsconfig
![800](https://user-images.githubusercontent.com/78641493/107155713-e3b12800-69b4-11eb-8a42-f6ecb78afb2e.png)
Then under src, I added folder and named like this
![cuck](https://user-images.githubusercontent.com/78641493/107155741-0e9b7c00-69b5-11eb-93a7-040fe921ac61.png)
But then it didn't recognise "@env", did I do smt wrong?

**Comment by goatandsheep** [comment]
@ericbaobao no problem! Try moving the `typeRoots` out of the `paths` object and let me know
https://www.typescriptlang.org/tsconfig#typeRoots

**Comment by ericbaobao** [comment]
> @ericbaobao no problem! Try moving the `typeRoots` out of the `paths` object and let me know. I love the screenshots. It helps a lot.
> https://www.typescriptlang.org/tsconfig#typeRoots

I tried hard search youtube video for configuration steps of typescript but I found none.
or it could be my mistake missing some steps, here is what I did:
1. yarn add -D react-native-dotenv
2. Do I need to add .env if I use typescript?
3. I don't have .babelrc so what I did is I add to **_babel.config.js_** "module:react-native-dotenv"
![one](https://user-images.githubusercontent.com/78641493/107157686-67bcdd00-69c0-11eb-8864-f29eec2c0106.png)
4. I'm sorry if I misunderstood it, you mean navigate to create a folder like this? ./node_modules/@env/
![likethis](https://user-images.githubusercontent.com/78641493/107157979-1d3c6000-69c2-11eb-8ad5-20c95f80f9d1.png)
5. I created a file inside called env.d.ts and pasted the code shown above
6. I have no idea what i am doing, this is the first time I do it by hand. Why is it "./src/types" ?
![imagine2](https://user-images.githubusercontent.com/78641493/107158206-7ce73b00-69c3-11eb-8f43-67ff1d92b318.png)
7. Then I navigate to one of the component and add **import { API_BASE } from '@env';**
![alpha](https://user-images.githubusercontent.com/78641493/107158265-01d25480-69c4-11eb-8f25-1792f28532e1.png)

Pretty sure I did something wrong in the steps, I am so sorry. Can you kindly show a guide please? @goatandsheep

**Comment by goatandsheep** [comment]
@ericbaobao no problem. Keep your environment-specific variables in the `.env` file.

For now, the wiki and readme are this guide. I may or may not be working on a new one 😉

**Comment by ericbaobao** [comment]
> @ericbaobao no problem. Keep your environment-specific variables in the `.env` file.
> 
> For now, the wiki and readme are the guides. I may or may not be working on a new one 😉

after adding the .env it is working now that you so much.
I wanted to ask you one last thing, is it correct if I write like this: "typeRoots": ["./node_modules/@env"],
if my steps in correct I can help you update the readme of your github if you want. Like the screenshot I posted here

**Comment by goatandsheep** [comment]
No that is not correct since `node_modules/@env` is generated by babel, unless the types were dynamically generated. Feel free to open a PR!

Your question gives me an idea for this ticket though. I mean when we get the feature completed to auto-generate the definitions file, we should definitely recommend that TS users use `node_modules/@env` for the types.

**Comment by ericbaobao** [comment]
> No that is not correct since `node_modules/@env` is generated by babel, unless the types were dynamically generated. Feel free to open a PR!
> 
> Your question gives me an idea for this ticket though. I mean when we get the feature completed to auto-generate the definitions file, we should definitely recommend that TS users use `node_modules/@env` for the types.

I didn't see babel generate anything in `node_modules/@env` . Not sure if it's a bug.
Just now I use the same steps to try in second project. In this one, the GUI is located inside src folder. It failed somehow, this is the warning it gave:
![alpha](https://user-images.githubusercontent.com/78641493/107163013-073e9780-69e2-11eb-92c3-dcab12925266.png)

Even I manually created a `@env` folder in node_modules the error still shows

**Comment by goatandsheep** [comment]
You should probably just put your typedef for `@env`, i.e. your constants, in `src/types`

**Comment by goatandsheep** [comment]
actually I thought of the easiest way for this to work. Instead of using `@env`, use `react-native-dotenv`, then change `moduleName` in `babel` config to `react-native-dotenv`.

**Comment by Hongbo-Miao** [comment]
`import { API_URL } from '@env';` works for me.

If I change to `import { API_URL } from 'react-native-dotenv';`, I got error

> Failed building JavaScript bundle.
> The package at "node_modules/react-native-dotenv/index.js" attempted to import the Node standard library module "fs". It failed because the native React runtime does not include the Node standard library. Read more at https://docs.expo.io/workflow/using-libraries/#using-third-party-libraries

**Comment by goatandsheep** [comment]
@Hongbo-Miao interesting using the `api.cache(true)`. I'm glad it's working. I'm going to start recommending people use https://www.npmjs.com/package/react-native-clean-project to clear the project on next Readme release
