### ISSUE TITLE
Change .env file before start app

### ISSUE THREAD

**Issue by NikonovichN** [goatandsheep/react-native-dotenv#73]
Hello, everyone!

I`m trying to change my .env before start app. It looks like that:

`npm run cd android && ./gradlew clean android && ./gradlew copySettings '-PFILE_SETTINGS=.env.testapp.dev' && cd .. && node node_modules/react-native/local-cli/cli.js run-android --variant=testappDebug --appIdSuffix 'debug' -- --reset-cache",`

But I always get one type of variables. Have any solutions for this case?

Thanks!

PS: react-native-config doesn`t fit, cause has problem with security.

**Comment by goatandsheep** [comment]
Only `.env.development`, `.env.test` and `.env.production` will work

**Comment by goatandsheep** [comment]
duplicated by #74
